### PR TITLE
Implemented method to prevent rotation of mapland maps in itemframes

### LINKED ISSUE #13: [Suggestion] Blocking the rotation/interaction of players with the map.
At the moment is it possible for players, to rotate a map from maplands, by simply right-clicking it in a item frame.
This is annoying and requires additional plugins like WorldGuard, to block it.
So it would be nice if maplands denies/blocks this action by default.

### LINKED ISSUE #14: [Question] Is there a check for if a Itemframe contains a map from maplands?
Question is in the title.
I wanted to ask, if there is a way, to check, if a itemframe has a map and if that map is from maplands.
I want to add a check to maplands that prevents the rotation of a map in a itemframe.
But I can't find out if (and if yes, where) maplands has such a check.

Could it be `MapUtil.isTile()`?

### PR DESCRIPTION
**Pull request by Andre601**
### Changes
- Added method to prevent players from rotating (rightclicking) a item frame, that contains a map from mapland. (Closes #13 and closes #14) 
- Made some methods and classes package-private or private because
  1. IntelliJ complained about that and
  2. It still works from my tests... (No guarantee tho)
- Added missing comments on javadoc description of a method.

### CODE REVIEW

**Comment by bergerkiller** [comment]
There's an awful lot of changes in field/method visibility that I'm not sure are really justified? Unless an IDE automatically decided these things as 'optimization'. I prefer to not change public to private (or package local) like this on a mass scale, they will only cause a lack of readability in the end.

...

I was about to say what bbayu just said, but yeah, there's an onRightClick event you can handle that not only cancels interaction with the map, but also with the block it is attached to. The logic to obtain the map display instance already exists inside BKCommonLib to create that event.

**Comment by Andre601** [comment]
I mentioned it in the comment, that the IDE (in this case IntelliJ) recommended those changes...
There was also one for the Permission class, which isn't possible because of BKCommonLib accessing it.

But honestly.
I leave that up to you to implement this stuff because I really think to is a bit too complicated for me to actually help with.

**Comment by bergerkiller** [comment]
Fair enough, I appreciate your efforts though! I see this is important to you, plus its quite easy to implement, so I'll go and add it for you now. It's easier for me to do since I understand the architecture I guess

**Comment by bergerkiller** [comment]
This should do it:
https://github.com/bergerhealer/Maplands/commit/bdc741b2ce4a23c72e47f71c783e5245e6cdf94b

https://ci.mg-dev.eu/job/Maplands/40/

**Comment by Andre601** [comment]
Yes this works

**Pull request closed without merging**
